// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.protobuff;

public final class AccountBook {
  private AccountBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AccountOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string acctNumber = 1;
    /**
     * <code>required string acctNumber = 1;</code>
     */
    boolean hasAcctNumber();
    /**
     * <code>required string acctNumber = 1;</code>
     */
    java.lang.String getAcctNumber();
    /**
     * <code>required string acctNumber = 1;</code>
     */
    com.google.protobuf.ByteString
        getAcctNumberBytes();

    // required string acctName = 2;
    /**
     * <code>required string acctName = 2;</code>
     */
    boolean hasAcctName();
    /**
     * <code>required string acctName = 2;</code>
     */
    java.lang.String getAcctName();
    /**
     * <code>required string acctName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAcctNameBytes();

    // required string acctHolderName = 3;
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    boolean hasAcctHolderName();
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    java.lang.String getAcctHolderName();
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    com.google.protobuf.ByteString
        getAcctHolderNameBytes();
  }
  /**
   * Protobuf type {@code tutorial.Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessage
      implements AccountOrBuilder {
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Account(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Account defaultInstance;
    public static Account getDefaultInstance() {
      return defaultInstance;
    }

    public Account getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              acctNumber_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              acctName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              acctHolderName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuff.AccountBook.internal_static_tutorial_Account_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuff.AccountBook.internal_static_tutorial_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuff.AccountBook.Account.class, com.protobuff.AccountBook.Account.Builder.class);
    }

    public static com.google.protobuf.Parser<Account> PARSER =
        new com.google.protobuf.AbstractParser<Account>() {
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string acctNumber = 1;
    public static final int ACCTNUMBER_FIELD_NUMBER = 1;
    private java.lang.Object acctNumber_;
    /**
     * <code>required string acctNumber = 1;</code>
     */
    public boolean hasAcctNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string acctNumber = 1;</code>
     */
    public java.lang.String getAcctNumber() {
      java.lang.Object ref = acctNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          acctNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string acctNumber = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAcctNumberBytes() {
      java.lang.Object ref = acctNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acctNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string acctName = 2;
    public static final int ACCTNAME_FIELD_NUMBER = 2;
    private java.lang.Object acctName_;
    /**
     * <code>required string acctName = 2;</code>
     */
    public boolean hasAcctName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string acctName = 2;</code>
     */
    public java.lang.String getAcctName() {
      java.lang.Object ref = acctName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          acctName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string acctName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAcctNameBytes() {
      java.lang.Object ref = acctName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acctName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string acctHolderName = 3;
    public static final int ACCTHOLDERNAME_FIELD_NUMBER = 3;
    private java.lang.Object acctHolderName_;
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    public boolean hasAcctHolderName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    public java.lang.String getAcctHolderName() {
      java.lang.Object ref = acctHolderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          acctHolderName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string acctHolderName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAcctHolderNameBytes() {
      java.lang.Object ref = acctHolderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acctHolderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      acctNumber_ = "";
      acctName_ = "";
      acctHolderName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAcctNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAcctName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAcctHolderName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAcctNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAcctNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAcctHolderNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAcctNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAcctNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAcctHolderNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuff.AccountBook.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuff.AccountBook.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuff.AccountBook.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuff.AccountBook.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuff.AccountBook.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuff.AccountBook.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuff.AccountBook.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuff.AccountBook.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuff.AccountBook.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuff.AccountBook.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuff.AccountBook.Account prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protobuff.AccountBook.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuff.AccountBook.internal_static_tutorial_Account_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuff.AccountBook.internal_static_tutorial_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuff.AccountBook.Account.class, com.protobuff.AccountBook.Account.Builder.class);
      }

      // Construct using com.protobuff.AccountBook.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        acctNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        acctName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        acctHolderName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuff.AccountBook.internal_static_tutorial_Account_descriptor;
      }

      public com.protobuff.AccountBook.Account getDefaultInstanceForType() {
        return com.protobuff.AccountBook.Account.getDefaultInstance();
      }

      public com.protobuff.AccountBook.Account build() {
        com.protobuff.AccountBook.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuff.AccountBook.Account buildPartial() {
        com.protobuff.AccountBook.Account result = new com.protobuff.AccountBook.Account(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.acctNumber_ = acctNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.acctName_ = acctName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.acctHolderName_ = acctHolderName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuff.AccountBook.Account) {
          return mergeFrom((com.protobuff.AccountBook.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuff.AccountBook.Account other) {
        if (other == com.protobuff.AccountBook.Account.getDefaultInstance()) return this;
        if (other.hasAcctNumber()) {
          bitField0_ |= 0x00000001;
          acctNumber_ = other.acctNumber_;
          onChanged();
        }
        if (other.hasAcctName()) {
          bitField0_ |= 0x00000002;
          acctName_ = other.acctName_;
          onChanged();
        }
        if (other.hasAcctHolderName()) {
          bitField0_ |= 0x00000004;
          acctHolderName_ = other.acctHolderName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAcctNumber()) {
          
          return false;
        }
        if (!hasAcctName()) {
          
          return false;
        }
        if (!hasAcctHolderName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuff.AccountBook.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuff.AccountBook.Account) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string acctNumber = 1;
      private java.lang.Object acctNumber_ = "";
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public boolean hasAcctNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public java.lang.String getAcctNumber() {
        java.lang.Object ref = acctNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          acctNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAcctNumberBytes() {
        java.lang.Object ref = acctNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acctNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public Builder setAcctNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        acctNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public Builder clearAcctNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        acctNumber_ = getDefaultInstance().getAcctNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string acctNumber = 1;</code>
       */
      public Builder setAcctNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        acctNumber_ = value;
        onChanged();
        return this;
      }

      // required string acctName = 2;
      private java.lang.Object acctName_ = "";
      /**
       * <code>required string acctName = 2;</code>
       */
      public boolean hasAcctName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string acctName = 2;</code>
       */
      public java.lang.String getAcctName() {
        java.lang.Object ref = acctName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          acctName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string acctName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAcctNameBytes() {
        java.lang.Object ref = acctName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acctName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string acctName = 2;</code>
       */
      public Builder setAcctName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        acctName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string acctName = 2;</code>
       */
      public Builder clearAcctName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        acctName_ = getDefaultInstance().getAcctName();
        onChanged();
        return this;
      }
      /**
       * <code>required string acctName = 2;</code>
       */
      public Builder setAcctNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        acctName_ = value;
        onChanged();
        return this;
      }

      // required string acctHolderName = 3;
      private java.lang.Object acctHolderName_ = "";
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public boolean hasAcctHolderName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public java.lang.String getAcctHolderName() {
        java.lang.Object ref = acctHolderName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          acctHolderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAcctHolderNameBytes() {
        java.lang.Object ref = acctHolderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acctHolderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public Builder setAcctHolderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        acctHolderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public Builder clearAcctHolderName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        acctHolderName_ = getDefaultInstance().getAcctHolderName();
        onChanged();
        return this;
      }
      /**
       * <code>required string acctHolderName = 3;</code>
       */
      public Builder setAcctHolderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        acctHolderName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Account)
    }

    static {
      defaultInstance = new Account(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Account)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Account_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\010tutorial\"G\n\007Account\022\022\n\n" +
      "acctNumber\030\001 \002(\t\022\020\n\010acctName\030\002 \002(\t\022\026\n\016ac" +
      "ctHolderName\030\003 \002(\tB\034\n\rcom.protobuffB\013Acc" +
      "ountBook"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Account_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Account_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Account_descriptor,
              new java.lang.String[] { "AcctNumber", "AcctName", "AcctHolderName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
